model_params:
  backend: 'distilled'
  model_id: ''
  model_size: 'medium'
  device: 'cpu'
  punctuate_truecase: False
generator_params:
  samplerate: 16000
  blocksize: 4000
  adjustment_time: 5
  min_chunks: 6
  memory_safe: True